# Generated by Django 4.1 on 2023-04-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('email_address', models.EmailField(db_column='email_address', max_length=200)),
                ('emp_id', models.CharField(db_column='emp_id', max_length=50)),
                ('division', models.CharField(blank=True, db_column='division', max_length=200, null=True)),
                ('organization', models.CharField(blank=True, db_column='organization', max_length=200, null=True)),
                ('position', models.CharField(blank=True, db_column='position', max_length=200, null=True)),
            ],
            options={
                'db_table': 'employee_details',
                'managed': True,
            },
        ),
    ]
